# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '5 13,14 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: run
      env:
        ID: ${{secrets.id}}
        PWS: ${{secrets.passwd}}
      run: |
        python ./main.py --username ID --password PWS --mail_user 13934248376 --mail_pass <mail_pass> --location 中国江苏省南京市栖霞区仙林大道 --mail_notify
